version: '3.8'

services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    ports:
      - "3210:3000"
    environment:
      - DATABASE_URL=file:/app/data/quiz.db
      - NEXT_PUBLIC_APP_URL=http://localhost:3210
    volumes:
      # Persist database
      - quiz-data:/app/data
      # Persist uploaded images
      - quiz-uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  quiz-data:
    driver: local
  quiz-uploads:
    driver: local
